# docker-compose.yaml for release branch

version: "3.9"
services:
  webservice:
    image: iwakura1ain/sejong-reservation-webservice:latest
    ports:
      - "80:80"

  reservationservice:
    image: iwakura1ain/sejong-reservation-reservationservice:latest

    environment:
      TZ: Asia/Seoul
      DB_URL: dbservice
      DB_NAME: sejong
      DB_PORT: 3306
      DB_USERNAME: development
      DB_PASSWORD: 1234
    ports:
      - "5000:5000"

  userservice:
    image: iwakura1ain/sejong-reservation-userservice:latest

    environment:
      TZ: Asia/Seoul
      DB_URL: dbservice
      DB_NAME: sejong
      DB_PORT: 3306
      DB_USERNAME: development
      DB_PASSWORD: 1234
    ports:
      - "5001:5001"

  managementservice:
    image: iwakura1ain/sejong-reservation-managementservice:latest

    environment:
      TZ: Asia/Seoul
      DB_URL: dbservice
      DB_NAME: sejong
      DB_PORT: 3306
      DB_USERNAME: development
      DB_PASSWORD: 1234
    ports:
      - "5002:5002"

  alertservice:
    image: iwakura1ain/sejong-reservation-alertservice:latest

    environment:
      TZ: Asia/Seoul
    ports:
      - "5003:5003"

  dbmanager:
    image: adminer:latest

    environment:
      TZ: Asia/Seoul
    # ports:
    #  - "9999:8080"

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   ports:
  #     - "9443:9443"
  #   volumes:
  #     - /home/dks/sejong-reservation/portainer-data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock

  dbservice:
    image: iwakura1ain/sejong-reservation-dbservice:latest
    environment:
      TZ: Asia/Seoul
      MYSQL_HOST: 0.0.0.0
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sejong
      MYSQL_USER: testusr
      MYSQL_PASSWORD: 1234

    ports:
      - "3306:3306"

  # dbservice:
  #   image: mariadb:11.0-rc-jammy
  #   env_file:
  #     ./DBService/maria-env
  #   environment:
  #     TZ: Asia/Seoul
  #   volumes:
  #     - ./DBService/maria-init.sql:/docker-entrypoint-initdb.d/maria-init.sql
  #   ports:
  #     - "3306:3306"

  # gatewayservice:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./Common/nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf
  #     - ./Common/nginx_proxy_params.conf:/etc/nginx/proxy_params
  #       # - /home/xx/Desktop/cust/xx/Docker/nginx/cert/star_xx_com.pem:/etc/nginx/cert/star_xx_com.pem
  #       # - /home/xx/Desktop/cust/xx/Docker/nginx/cert/star_xx_com.key:/etc/nginx/cert/star_xx_com.key
  #       # - /home/xx/Desktop/cust/xx/Docker/nginx/cert/star_xx_com.crt:/etc/nginx/cert/star_xx_com.crt
  #   environment:
  #     TZ: Asia/Seoul
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - reservationservice
  #     - userservice
  #     - managementservice
  #     - alertservice
  #     - dbservice

  gatewayservice:
    image: iwakura1ain/sejong-reservation-gatewayservice:latest

    environment:
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    depends_on:
      - reservationservice
      - userservice
      - managementservice
      - alertservice
      - dbservice

# volumes:
#     portainer-data:
