DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
       id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       username VARCHAR(20) NOT NULL,
       password VARCHAR(128) NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE Post (
       id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       author_id INT NOT NULL,
       created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
       title VARCHAR(20) NOT NULL,
       body VARCHAR(100) NOT NULL,
       CONSTRAINT Post_User
       FOREIGN KEY (author_id) REFERENCES User(id)
) DEFAULT CHARSET=utf8;



