name: Test Build
run-name: Test Build

on:
  push:
    branches:
      - 'release-*'
    paths:
      - 'WebService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: 19.x

      - name: Install dependencies
        working-directory: ./WebService/vue-project
        run: npm ci

      # # 4. 테스트
      # - name: Test unit
      #   run: npm run test:unit

      # 5. 빌드
      - name: Build Page
        working-directory: ./WebService/vue-project
        run: npm run build
